-- 
-- supression des tables si elles existent.
--
DROP TABLE SPORTIFS;
DROP TABLE PAYS;

--creation de la table des pays
CREATE TABLE PAYS (
   ID VARCHAR2(2) NOT NULL,
   NOM VARCHAR2(64) NOT NULL,
   PRIMARY KEY (ID));

-- creation de la table des sportifs
CREATE TABLE SPORTIFS (
   ID_SPORTIF NUMBER(38) NOT NULL,
   NOM VARCHAR2(32) NOT NULL,
   PRENOM VARCHAR2(32) NOT NULL,
   SEXE VARCHAR2(1),
   PAYS VARCHAR2(2),
   PRIMARY KEY (ID_SPORTIF));

--
-- création des pays
Insert into PAYS (ID,NOM) values ('ZA','Afrique du Sud');
Insert into PAYS (ID,NOM) values ('AF','Afghanistan');
Insert into PAYS (ID,NOM) values ('AL','Albanie');
Insert into PAYS (ID,NOM) values ('DZ','Algérie');
Insert into PAYS (ID,NOM) values ('DE','Allemagne');
Insert into PAYS (ID,NOM) values ('AD','Andorre');
Insert into PAYS (ID,NOM) values ('AO','Angola');
Insert into PAYS (ID,NOM) values ('AI','Anguilla');
Insert into PAYS (ID,NOM) values ('AQ','Antarctique');
Insert into PAYS (ID,NOM) values ('AG','Antigua-et-Barbuda');
Insert into PAYS (ID,NOM) values ('SA','Arabie saoudite');
Insert into PAYS (ID,NOM) values ('AR','Argentine');
Insert into PAYS (ID,NOM) values ('AM','Arménie');
Insert into PAYS (ID,NOM) values ('AW','Aruba');
Insert into PAYS (ID,NOM) values ('AU','Australie');
Insert into PAYS (ID,NOM) values ('AT','Autriche');
Insert into PAYS (ID,NOM) values ('AZ','Azerbaïdjan');
Insert into PAYS (ID,NOM) values ('BS','Bahamas');
Insert into PAYS (ID,NOM) values ('BH','Bahreïn');
Insert into PAYS (ID,NOM) values ('BD','Bangladesh');
Insert into PAYS (ID,NOM) values ('BB','Barbade');
Insert into PAYS (ID,NOM) values ('BE','Belgique');
Insert into PAYS (ID,NOM) values ('BZ','Belize');
Insert into PAYS (ID,NOM) values ('BJ','Bénin');
Insert into PAYS (ID,NOM) values ('BM','Bermudes');
Insert into PAYS (ID,NOM) values ('BT','Bhoutan');
Insert into PAYS (ID,NOM) values ('BY','Biélorussie');
Insert into PAYS (ID,NOM) values ('BO','Bolivie');
Insert into PAYS (ID,NOM) values ('BA','Bosnie-Herzégovine');
Insert into PAYS (ID,NOM) values ('BW','Botswana');
Insert into PAYS (ID,NOM) values ('BR','Brésil');
Insert into PAYS (ID,NOM) values ('BN','Brunéi Darussalam');
Insert into PAYS (ID,NOM) values ('BG','Bulgarie');
Insert into PAYS (ID,NOM) values ('BF','Burkina Faso');
Insert into PAYS (ID,NOM) values ('BI','Burundi');
Insert into PAYS (ID,NOM) values ('KH','Cambodge');
Insert into PAYS (ID,NOM) values ('CM','Cameroun');
Insert into PAYS (ID,NOM) values ('CA','Canada');
Insert into PAYS (ID,NOM) values ('CV','Cap-Vert');
Insert into PAYS (ID,NOM) values ('EA','Ceuta et Melilla');
Insert into PAYS (ID,NOM) values ('CL','Chili');
Insert into PAYS (ID,NOM) values ('CN','Chine');
Insert into PAYS (ID,NOM) values ('CY','Chypre');
Insert into PAYS (ID,NOM) values ('CO','Colombie');
Insert into PAYS (ID,NOM) values ('KM','Comores');
Insert into PAYS (ID,NOM) values ('CG','Congo-Brazzaville');
Insert into PAYS (ID,NOM) values ('CD','Congo-Kinshasa');
Insert into PAYS (ID,NOM) values ('KP','Corée du Nord');
Insert into PAYS (ID,NOM) values ('KR','Corée du Sud');
Insert into PAYS (ID,NOM) values ('CR','Costa Rica');
Insert into PAYS (ID,NOM) values ('CI','Côte d’Ivoire');
Insert into PAYS (ID,NOM) values ('HR','Croatie');
Insert into PAYS (ID,NOM) values ('CU','Cuba');
Insert into PAYS (ID,NOM) values ('CW','Curaçao');
Insert into PAYS (ID,NOM) values ('DK','Danemark');
Insert into PAYS (ID,NOM) values ('DG','Diego Garcia');
Insert into PAYS (ID,NOM) values ('DJ','Djibouti');
Insert into PAYS (ID,NOM) values ('DM','Dominique');
Insert into PAYS (ID,NOM) values ('EG','Égypte');
Insert into PAYS (ID,NOM) values ('SV','El Salvador');
Insert into PAYS (ID,NOM) values ('AE','Émirats arabes unis');
Insert into PAYS (ID,NOM) values ('EC','Équateur');
Insert into PAYS (ID,NOM) values ('ER','Érythrée');
Insert into PAYS (ID,NOM) values ('ES','Espagne');
Insert into PAYS (ID,NOM) values ('EE','Estonie');
Insert into PAYS (ID,NOM) values ('VA','État de la Cité du Vatican');
Insert into PAYS (ID,NOM) values ('FM','États fédérés de Micronésie');
Insert into PAYS (ID,NOM) values ('US','États-Unis');
Insert into PAYS (ID,NOM) values ('ET','Éthiopie');
Insert into PAYS (ID,NOM) values ('FJ','Fidji');
Insert into PAYS (ID,NOM) values ('FI','Finlande');
Insert into PAYS (ID,NOM) values ('FR','France');
Insert into PAYS (ID,NOM) values ('GA','Gabon');
Insert into PAYS (ID,NOM) values ('GM','Gambie');
Insert into PAYS (ID,NOM) values ('GE','Géorgie');
Insert into PAYS (ID,NOM) values ('GH','Ghana');
Insert into PAYS (ID,NOM) values ('GI','Gibraltar');
Insert into PAYS (ID,NOM) values ('GR','Grèce');
Insert into PAYS (ID,NOM) values ('GD','Grenade');
Insert into PAYS (ID,NOM) values ('GL','Groenland');
Insert into PAYS (ID,NOM) values ('GP','Guadeloupe');
Insert into PAYS (ID,NOM) values ('GU','Guam');
Insert into PAYS (ID,NOM) values ('GT','Guatemala');
Insert into PAYS (ID,NOM) values ('GG','Guernesey');
Insert into PAYS (ID,NOM) values ('GN','Guinée');
Insert into PAYS (ID,NOM) values ('GQ','Guinée équatoriale');
Insert into PAYS (ID,NOM) values ('GW','Guinée-Bissau');
Insert into PAYS (ID,NOM) values ('GY','Guyana');
Insert into PAYS (ID,NOM) values ('GF','Guyane française');
Insert into PAYS (ID,NOM) values ('HT','Haïti');
Insert into PAYS (ID,NOM) values ('HN','Honduras');
Insert into PAYS (ID,NOM) values ('HU','Hongrie');
Insert into PAYS (ID,NOM) values ('CX','Île Christmas');
Insert into PAYS (ID,NOM) values ('AC','Île de l’Ascension');
Insert into PAYS (ID,NOM) values ('IM','Île de Man');
Insert into PAYS (ID,NOM) values ('NF','Île Norfolk');
Insert into PAYS (ID,NOM) values ('AX','Îles Åland');
Insert into PAYS (ID,NOM) values ('KY','Îles Caïmans');
Insert into PAYS (ID,NOM) values ('IC','Îles Canaries');
Insert into PAYS (ID,NOM) values ('CC','Îles Cocos');
Insert into PAYS (ID,NOM) values ('CK','Îles Cook');
Insert into PAYS (ID,NOM) values ('FO','Îles Féroé');
Insert into PAYS (ID,NOM) values ('GS','Îles Géorgie du Sud et Sandwich du Sud');
Insert into PAYS (ID,NOM) values ('FK','Îles Malouines');
Insert into PAYS (ID,NOM) values ('MP','Îles Mariannes du Nord');
Insert into PAYS (ID,NOM) values ('MH','Îles Marshall');
Insert into PAYS (ID,NOM) values ('UM','Îles mineures éloignées des États-Unis');
Insert into PAYS (ID,NOM) values ('SB','Îles Salomon');
Insert into PAYS (ID,NOM) values ('TC','Îles Turques-et-Caïques');
Insert into PAYS (ID,NOM) values ('VG','Îles Vierges britanniques');
Insert into PAYS (ID,NOM) values ('VI','Îles Vierges des États-Unis');
Insert into PAYS (ID,NOM) values ('IN','Inde');
Insert into PAYS (ID,NOM) values ('ID','Indonésie');
Insert into PAYS (ID,NOM) values ('IQ','Irak');
Insert into PAYS (ID,NOM) values ('IR','Iran');
Insert into PAYS (ID,NOM) values ('IE','Irlande');
Insert into PAYS (ID,NOM) values ('IS','Islande');
Insert into PAYS (ID,NOM) values ('IL','Israël');
Insert into PAYS (ID,NOM) values ('IT','Italie');
Insert into PAYS (ID,NOM) values ('JM','Jamaïque');
Insert into PAYS (ID,NOM) values ('JP','Japon');
Insert into PAYS (ID,NOM) values ('JE','Jersey');
Insert into PAYS (ID,NOM) values ('JO','Jordanie');
Insert into PAYS (ID,NOM) values ('KZ','Kazakhstan');
Insert into PAYS (ID,NOM) values ('KE','Kenya');
Insert into PAYS (ID,NOM) values ('KG','Kirghizistan');
Insert into PAYS (ID,NOM) values ('KI','Kiribati');
Insert into PAYS (ID,NOM) values ('XK','Kosovo');
Insert into PAYS (ID,NOM) values ('KW','Koweït');
Insert into PAYS (ID,NOM) values ('RE','La Réunion');
Insert into PAYS (ID,NOM) values ('LA','Laos');
Insert into PAYS (ID,NOM) values ('LS','Lesotho');
Insert into PAYS (ID,NOM) values ('LV','Lettonie');
Insert into PAYS (ID,NOM) values ('LB','Liban');
Insert into PAYS (ID,NOM) values ('LR','Libéria');
Insert into PAYS (ID,NOM) values ('LY','Libye');
Insert into PAYS (ID,NOM) values ('LI','Liechtenstein');
Insert into PAYS (ID,NOM) values ('LT','Lituanie');
Insert into PAYS (ID,NOM) values ('LU','Luxembourg');
Insert into PAYS (ID,NOM) values ('MK','Macédoine');
Insert into PAYS (ID,NOM) values ('MG','Madagascar');
Insert into PAYS (ID,NOM) values ('MY','Malaisie');
Insert into PAYS (ID,NOM) values ('MW','Malawi');
Insert into PAYS (ID,NOM) values ('MV','Maldives');
Insert into PAYS (ID,NOM) values ('ML','Mali');
Insert into PAYS (ID,NOM) values ('MT','Malte');
Insert into PAYS (ID,NOM) values ('MA','Maroc');
Insert into PAYS (ID,NOM) values ('MQ','Martinique');
Insert into PAYS (ID,NOM) values ('MU','Maurice');
Insert into PAYS (ID,NOM) values ('MR','Mauritanie');
Insert into PAYS (ID,NOM) values ('YT','Mayotte');
Insert into PAYS (ID,NOM) values ('MX','Mexique');
Insert into PAYS (ID,NOM) values ('MD','Moldavie');
Insert into PAYS (ID,NOM) values ('MC','Monaco');
Insert into PAYS (ID,NOM) values ('MN','Mongolie');
Insert into PAYS (ID,NOM) values ('ME','Monténégro');
Insert into PAYS (ID,NOM) values ('MS','Montserrat');
Insert into PAYS (ID,NOM) values ('MZ','Mozambique');
Insert into PAYS (ID,NOM) values ('MM','Myanmar');
Insert into PAYS (ID,NOM) values ('NA','Namibie');
Insert into PAYS (ID,NOM) values ('NR','Nauru');
Insert into PAYS (ID,NOM) values ('NP','Népal');
Insert into PAYS (ID,NOM) values ('NI','Nicaragua');
Insert into PAYS (ID,NOM) values ('NE','Niger');
Insert into PAYS (ID,NOM) values ('NG','Nigéria');
Insert into PAYS (ID,NOM) values ('NU','Niue');
Insert into PAYS (ID,NOM) values ('NO','Norvège');
Insert into PAYS (ID,NOM) values ('NC','Nouvelle-Calédonie');
Insert into PAYS (ID,NOM) values ('NZ','Nouvelle-Zélande');
Insert into PAYS (ID,NOM) values ('OM','Oman');
Insert into PAYS (ID,NOM) values ('UG','Ouganda');
Insert into PAYS (ID,NOM) values ('UZ','Ouzbékistan');
Insert into PAYS (ID,NOM) values ('PK','Pakistan');
Insert into PAYS (ID,NOM) values ('PW','Palaos');
Insert into PAYS (ID,NOM) values ('PA','Panama');
Insert into PAYS (ID,NOM) values ('PG','Papouasie-Nouvelle-Guinée');
Insert into PAYS (ID,NOM) values ('PY','Paraguay');
Insert into PAYS (ID,NOM) values ('NL','Pays-Bas');
Insert into PAYS (ID,NOM) values ('BQ','Pays-Bas caribéens');
Insert into PAYS (ID,NOM) values ('PE','Pérou');
Insert into PAYS (ID,NOM) values ('PH','Philippines');
Insert into PAYS (ID,NOM) values ('PN','Pitcairn');
Insert into PAYS (ID,NOM) values ('PL','Pologne');
Insert into PAYS (ID,NOM) values ('PF','Polynésie française');
Insert into PAYS (ID,NOM) values ('PR','Porto Rico');
Insert into PAYS (ID,NOM) values ('PT','Portugal');
Insert into PAYS (ID,NOM) values ('QA','Qatar');
Insert into PAYS (ID,NOM) values ('HK','R.A.S. chinoise de Hong Kong');
Insert into PAYS (ID,NOM) values ('MO','R.A.S. chinoise de Macao');
Insert into PAYS (ID,NOM) values ('CF','République centrafricaine');
Insert into PAYS (ID,NOM) values ('DO','République dominicaine');
Insert into PAYS (ID,NOM) values ('CZ','République tchèque');
Insert into PAYS (ID,NOM) values ('RO','Roumanie');
Insert into PAYS (ID,NOM) values ('GB','Royaume-Uni');
Insert into PAYS (ID,NOM) values ('RU','Russie');
Insert into PAYS (ID,NOM) values ('RW','Rwanda');
Insert into PAYS (ID,NOM) values ('EH','Sahara occidental');
Insert into PAYS (ID,NOM) values ('BL','Saint-Barthélemy');
Insert into PAYS (ID,NOM) values ('KN','Saint-Christophe-et-Niévès');
Insert into PAYS (ID,NOM) values ('SM','Saint-Marin');
Insert into PAYS (ID,NOM) values ('MF','Saint-Martin (partie française)');
Insert into PAYS (ID,NOM) values ('SX','Saint-Martin (partie néerlandaise)');
Insert into PAYS (ID,NOM) values ('PM','Saint-Pierre-et-Miquelon');
Insert into PAYS (ID,NOM) values ('VC','Saint-Vincent-et-les-Grenadines');
Insert into PAYS (ID,NOM) values ('SH','Sainte-Hélène');
Insert into PAYS (ID,NOM) values ('LC','Sainte-Lucie');
Insert into PAYS (ID,NOM) values ('WS','Samoa');
Insert into PAYS (ID,NOM) values ('AS','Samoa américaines');
Insert into PAYS (ID,NOM) values ('ST','Sao Tomé-et-Principe');
Insert into PAYS (ID,NOM) values ('SN','Sénégal');
Insert into PAYS (ID,NOM) values ('RS','Serbie');
Insert into PAYS (ID,NOM) values ('SC','Seychelles');
Insert into PAYS (ID,NOM) values ('SL','Sierra Leone');
Insert into PAYS (ID,NOM) values ('SG','Singapour');
Insert into PAYS (ID,NOM) values ('SK','Slovaquie');
Insert into PAYS (ID,NOM) values ('SI','Slovénie');
Insert into PAYS (ID,NOM) values ('SO','Somalie');
Insert into PAYS (ID,NOM) values ('SD','Soudan');
Insert into PAYS (ID,NOM) values ('SS','Soudan du Sud');
Insert into PAYS (ID,NOM) values ('LK','Sri Lanka');
Insert into PAYS (ID,NOM) values ('SE','Suède');
Insert into PAYS (ID,NOM) values ('CH','Suisse');
Insert into PAYS (ID,NOM) values ('SR','Suriname');
Insert into PAYS (ID,NOM) values ('SJ','Svalbard et Jan Mayen');
Insert into PAYS (ID,NOM) values ('SZ','Swaziland');
Insert into PAYS (ID,NOM) values ('SY','Syrie');
Insert into PAYS (ID,NOM) values ('TJ','Tadjikistan');
Insert into PAYS (ID,NOM) values ('TW','Taïwan');
Insert into PAYS (ID,NOM) values ('TZ','Tanzanie');
Insert into PAYS (ID,NOM) values ('TD','Tchad');
Insert into PAYS (ID,NOM) values ('TF','Terres australes françaises');
Insert into PAYS (ID,NOM) values ('IO','Territoire britannique de l’océan Indien');
Insert into PAYS (ID,NOM) values ('PS','Territoires palestiniens');
Insert into PAYS (ID,NOM) values ('TH','Thaïlande');
Insert into PAYS (ID,NOM) values ('TL','Timor oriental');
Insert into PAYS (ID,NOM) values ('TG','Togo');
Insert into PAYS (ID,NOM) values ('TK','Tokelau');
Insert into PAYS (ID,NOM) values ('TO','Tonga');
Insert into PAYS (ID,NOM) values ('TT','Trinité-et-Tobago');
Insert into PAYS (ID,NOM) values ('TA','Tristan da Cunha');
Insert into PAYS (ID,NOM) values ('TN','Tunisie');
Insert into PAYS (ID,NOM) values ('TM','Turkménistan');
Insert into PAYS (ID,NOM) values ('TR','Turquie');
Insert into PAYS (ID,NOM) values ('TV','Tuvalu');
Insert into PAYS (ID,NOM) values ('UA','Ukraine');
Insert into PAYS (ID,NOM) values ('UY','Uruguay');
Insert into PAYS (ID,NOM) values ('VU','Vanuatu');
Insert into PAYS (ID,NOM) values ('VE','Venezuela');
Insert into PAYS (ID,NOM) values ('VN','Vietnam');
Insert into PAYS (ID,NOM) values ('WF','Wallis-et-Futuna');
Insert into PAYS (ID,NOM) values ('YE','Yémen');
Insert into PAYS (ID,NOM) values ('ZM','Zambie');
Insert into PAYS (ID,NOM) values ('ZW','Zimbabwe');

--
-- création des sportifs
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('2','MOUNIER','Laurent','M','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('3','FAVRE','Jean-Marie','M','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('4','SICARD','Pascal','M','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('5','WAILLE','Philippe','M','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('6','GENOUD','Philippe','M','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('7','FAUVET','Marie-Christine','F','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('8','PARENT-VIGOUROUX','Catherine','F','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('9','CAFIAUX','Sybille','F','FR');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('10','MOONIER','Laurent','M','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('11','FAVRE','John','M','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('12','SEECARD','Pascal','M','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('13','WAILLE','Philip','M','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('14','KNEE','Philip','M','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('15','WARBLER','Mary','F','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('16','PARENT-VIGOUROUS','Catherine','F','US');
Insert into SPORTIFS (ID_SPORTIF,NOM,PRENOM,SEXE,PAYS) values ('17','KAFIO','Sybille','F','US');
