DROP TABLE SPORTIFS;
DROP SEQUENCE NUM_SPORTIF;

CREATE SEQUENCE NUM_SPORTIF;

CREATE TABLE SPORTIFS (
   id_sportif INTEGER NOT NULL,
   Nom VARCHAR(32) NOT NULL,
   PreNom VARCHAR(32) NOT NULL,
   Sexe VARCHAR(1) CHECK( Sexe IN ('M','F')),
   Pays VARCHAR(2),
   FOREIGN KEY (Pays) REFERENCES Pays(id),
   PRIMARY KEY(id_sportif)
);

INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'MOUNIER','Laurent', 'M', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'FAVRE','Jean-Marie', 'M', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'SICARD','Pascal', 'M', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'WAILLE','Philippe', 'M', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'GENOUD','Philippe', 'M', 'FR');

INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'FAUVET','Marie-Christine', 'F', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'PARENT-VIGOUROUX','Catherine', 'F', 'FR');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'CAFIAUX','Sybille', 'F', 'FR');

INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'MOONIER','Laurent', 'M', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'FAVRE','John', 'M', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'SEECARD','Pascal', 'M', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'WAILLE','Philip', 'M', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'KNEE','Philip', 'M', 'US');

INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'WARBLER','Mary', 'F', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'PARENT-VIGOUROUS','Catherine', 'F', 'US');
INSERT INTO SPORTIFS VALUES(NUM_SPORTIF.NEXTVAL,'KAFIO','Sybille', 'F', 'US');

SELECT ID_SPORTIF,CONCAT(NOM, CONCAT(' ', PRENOM)) FROM SPORTIFS WHERE Pays='US' and Sexe = 'M'