DROP TABLE PAYS;

CREATE TABLE PAYS (id VARCHAR(2) NOT NULL,
 Nom VARCHAR(64) NOT NULL,
 PRIMARY KEY(id));

INSERT INTO "PAYS" (id, Nom) VALUES ('ZA', 'Afrique du Sud');
INSERT INTO "PAYS" (id, Nom) VALUES ('AF', 'Afghanistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('ZA', 'Afrique du Sud');
INSERT INTO "PAYS" (id, Nom) VALUES ('AL', 'Albanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('DZ', 'Algérie');
INSERT INTO "PAYS" (id, Nom) VALUES ('DE', 'Allemagne');
INSERT INTO "PAYS" (id, Nom) VALUES ('AD', 'Andorre');
INSERT INTO "PAYS" (id, Nom) VALUES ('AO', 'Angola');
INSERT INTO "PAYS" (id, Nom) VALUES ('AI', 'Anguilla');
INSERT INTO "PAYS" (id, Nom) VALUES ('AQ', 'Antarctique');
INSERT INTO "PAYS" (id, Nom) VALUES ('AG', 'Antigua-et-Barbuda');
INSERT INTO "PAYS" (id, Nom) VALUES ('SA', 'Arabie saoudite');
INSERT INTO "PAYS" (id, Nom) VALUES ('AR', 'Argentine');
INSERT INTO "PAYS" (id, Nom) VALUES ('AM', 'Arménie');
INSERT INTO "PAYS" (id, Nom) VALUES ('AW', 'Aruba');
INSERT INTO "PAYS" (id, Nom) VALUES ('AU', 'Australie');
INSERT INTO "PAYS" (id, Nom) VALUES ('AT', 'Autriche');
INSERT INTO "PAYS" (id, Nom) VALUES ('AZ', 'Azerbaïdjan');
INSERT INTO "PAYS" (id, Nom) VALUES ('BS', 'Bahamas');
INSERT INTO "PAYS" (id, Nom) VALUES ('BH', 'Bahreïn');
INSERT INTO "PAYS" (id, Nom) VALUES ('BD', 'Bangladesh');
INSERT INTO "PAYS" (id, Nom) VALUES ('BB', 'Barbade');
INSERT INTO "PAYS" (id, Nom) VALUES ('BE', 'Belgique');
INSERT INTO "PAYS" (id, Nom) VALUES ('BZ', 'Belize');
INSERT INTO "PAYS" (id, Nom) VALUES ('BJ', 'Bénin');
INSERT INTO "PAYS" (id, Nom) VALUES ('BM', 'Bermudes');
INSERT INTO "PAYS" (id, Nom) VALUES ('BT', 'Bhoutan');
INSERT INTO "PAYS" (id, Nom) VALUES ('BY', 'Biélorussie');
INSERT INTO "PAYS" (id, Nom) VALUES ('BO', 'Bolivie');
INSERT INTO "PAYS" (id, Nom) VALUES ('BA', 'Bosnie-Herzégovine');
INSERT INTO "PAYS" (id, Nom) VALUES ('BW', 'Botswana');
INSERT INTO "PAYS" (id, Nom) VALUES ('BR', 'Brésil');
INSERT INTO "PAYS" (id, Nom) VALUES ('BN', 'Brunéi Darussalam');
INSERT INTO "PAYS" (id, Nom) VALUES ('BG', 'Bulgarie');
INSERT INTO "PAYS" (id, Nom) VALUES ('BF', 'Burkina Faso');
INSERT INTO "PAYS" (id, Nom) VALUES ('BI', 'Burundi');
INSERT INTO "PAYS" (id, Nom) VALUES ('KH', 'Cambodge');
INSERT INTO "PAYS" (id, Nom) VALUES ('CM', 'Cameroun');
INSERT INTO "PAYS" (id, Nom) VALUES ('CA', 'Canada');
INSERT INTO "PAYS" (id, Nom) VALUES ('CV', 'Cap-Vert');
INSERT INTO "PAYS" (id, Nom) VALUES ('EA', 'Ceuta et Melilla');
INSERT INTO "PAYS" (id, Nom) VALUES ('CL', 'Chili');
INSERT INTO "PAYS" (id, Nom) VALUES ('CN', 'Chine');
INSERT INTO "PAYS" (id, Nom) VALUES ('CY', 'Chypre');
INSERT INTO "PAYS" (id, Nom) VALUES ('CO', 'Colombie');
INSERT INTO "PAYS" (id, Nom) VALUES ('KM', 'Comores');
INSERT INTO "PAYS" (id, Nom) VALUES ('CG', 'Congo-Brazzaville');
INSERT INTO "PAYS" (id, Nom) VALUES ('CD', 'Congo-Kinshasa');
INSERT INTO "PAYS" (id, Nom) VALUES ('KP', 'Corée du Nord');
INSERT INTO "PAYS" (id, Nom) VALUES ('KR', 'Corée du Sud');
INSERT INTO "PAYS" (id, Nom) VALUES ('CR', 'Costa Rica');
INSERT INTO "PAYS" (id, Nom) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO "PAYS" (id, Nom) VALUES ('HR', 'Croatie');
INSERT INTO "PAYS" (id, Nom) VALUES ('CU', 'Cuba');
INSERT INTO "PAYS" (id, Nom) VALUES ('CW', 'Curaçao');
INSERT INTO "PAYS" (id, Nom) VALUES ('DK', 'Danemark');
INSERT INTO "PAYS" (id, Nom) VALUES ('DG', 'Diego Garcia');
INSERT INTO "PAYS" (id, Nom) VALUES ('DJ', 'Djibouti');
INSERT INTO "PAYS" (id, Nom) VALUES ('DM', 'Dominique');
INSERT INTO "PAYS" (id, Nom) VALUES ('EG', 'Égypte');
INSERT INTO "PAYS" (id, Nom) VALUES ('SV', 'El Salvador');
INSERT INTO "PAYS" (id, Nom) VALUES ('AE', 'Émirats arabes unis');
INSERT INTO "PAYS" (id, Nom) VALUES ('EC', 'Équateur');
INSERT INTO "PAYS" (id, Nom) VALUES ('ER', 'Érythrée');
INSERT INTO "PAYS" (id, Nom) VALUES ('ES', 'Espagne');
INSERT INTO "PAYS" (id, Nom) VALUES ('EE', 'Estonie');
INSERT INTO "PAYS" (id, Nom) VALUES ('VA', 'État de la Cité du Vatican');
INSERT INTO "PAYS" (id, Nom) VALUES ('FM', 'États fédérés de Micronésie');
INSERT INTO "PAYS" (id, Nom) VALUES ('US', 'États-Unis');
INSERT INTO "PAYS" (id, Nom) VALUES ('ET', 'Éthiopie');
INSERT INTO "PAYS" (id, Nom) VALUES ('FJ', 'Fidji');
INSERT INTO "PAYS" (id, Nom) VALUES ('FI', 'Finlande');
INSERT INTO "PAYS" (id, Nom) VALUES ('FR', 'France');
INSERT INTO "PAYS" (id, Nom) VALUES ('GA', 'Gabon');
INSERT INTO "PAYS" (id, Nom) VALUES ('GM', 'Gambie');
INSERT INTO "PAYS" (id, Nom) VALUES ('GE', 'Géorgie');
INSERT INTO "PAYS" (id, Nom) VALUES ('GH', 'Ghana');
INSERT INTO "PAYS" (id, Nom) VALUES ('GI', 'Gibraltar');
INSERT INTO "PAYS" (id, Nom) VALUES ('GR', 'Grèce');
INSERT INTO "PAYS" (id, Nom) VALUES ('GD', 'Grenade');
INSERT INTO "PAYS" (id, Nom) VALUES ('GL', 'Groenland');
INSERT INTO "PAYS" (id, Nom) VALUES ('GP', 'Guadeloupe');
INSERT INTO "PAYS" (id, Nom) VALUES ('GU', 'Guam');
INSERT INTO "PAYS" (id, Nom) VALUES ('GT', 'Guatemala');
INSERT INTO "PAYS" (id, Nom) VALUES ('GG', 'Guernesey');
INSERT INTO "PAYS" (id, Nom) VALUES ('GN', 'Guinée');
INSERT INTO "PAYS" (id, Nom) VALUES ('GQ', 'Guinée équatoriale');
INSERT INTO "PAYS" (id, Nom) VALUES ('GW', 'Guinée-Bissau');
INSERT INTO "PAYS" (id, Nom) VALUES ('GY', 'Guyana');
INSERT INTO "PAYS" (id, Nom) VALUES ('GF', 'Guyane française');
INSERT INTO "PAYS" (id, Nom) VALUES ('HT', 'Haïti');
INSERT INTO "PAYS" (id, Nom) VALUES ('HN', 'Honduras');
INSERT INTO "PAYS" (id, Nom) VALUES ('HU', 'Hongrie');
INSERT INTO "PAYS" (id, Nom) VALUES ('CX', 'Île Christmas');
INSERT INTO "PAYS" (id, Nom) VALUES ('AC', 'Île de l’Ascension');
INSERT INTO "PAYS" (id, Nom) VALUES ('IM', 'Île de Man');
INSERT INTO "PAYS" (id, Nom) VALUES ('NF', 'Île Norfolk');
INSERT INTO "PAYS" (id, Nom) VALUES ('AX', 'Îles Åland');
INSERT INTO "PAYS" (id, Nom) VALUES ('KY', 'Îles Caïmans');
INSERT INTO "PAYS" (id, Nom) VALUES ('IC', 'Îles Canaries');
INSERT INTO "PAYS" (id, Nom) VALUES ('CC', 'Îles Cocos');
INSERT INTO "PAYS" (id, Nom) VALUES ('CK', 'Îles Cook');
INSERT INTO "PAYS" (id, Nom) VALUES ('FO', 'Îles Féroé');
INSERT INTO "PAYS" (id, Nom) VALUES ('GS', 'Îles Géorgie du Sud et Sandwich du Sud');
INSERT INTO "PAYS" (id, Nom) VALUES ('FK', 'Îles Malouines');
INSERT INTO "PAYS" (id, Nom) VALUES ('MP', 'Îles Mariannes du Nord');
INSERT INTO "PAYS" (id, Nom) VALUES ('MH', 'Îles Marshall');
INSERT INTO "PAYS" (id, Nom) VALUES ('UM', 'Îles mineures éloignées des États-Unis');
INSERT INTO "PAYS" (id, Nom) VALUES ('SB', 'Îles Salomon');
INSERT INTO "PAYS" (id, Nom) VALUES ('TC', 'Îles Turques-et-Caïques');
INSERT INTO "PAYS" (id, Nom) VALUES ('VG', 'Îles Vierges britanniques');
INSERT INTO "PAYS" (id, Nom) VALUES ('VI', 'Îles Vierges des États-Unis');
INSERT INTO "PAYS" (id, Nom) VALUES ('IN', 'Inde');
INSERT INTO "PAYS" (id, Nom) VALUES ('ID', 'Indonésie');
INSERT INTO "PAYS" (id, Nom) VALUES ('IQ', 'Irak');
INSERT INTO "PAYS" (id, Nom) VALUES ('IR', 'Iran');
INSERT INTO "PAYS" (id, Nom) VALUES ('IE', 'Irlande');
INSERT INTO "PAYS" (id, Nom) VALUES ('IS', 'Islande');
INSERT INTO "PAYS" (id, Nom) VALUES ('IL', 'Israël');
INSERT INTO "PAYS" (id, Nom) VALUES ('IT', 'Italie');
INSERT INTO "PAYS" (id, Nom) VALUES ('JM', 'Jamaïque');
INSERT INTO "PAYS" (id, Nom) VALUES ('JP', 'Japon');
INSERT INTO "PAYS" (id, Nom) VALUES ('JE', 'Jersey');
INSERT INTO "PAYS" (id, Nom) VALUES ('JO', 'Jordanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('KZ', 'Kazakhstan');
INSERT INTO "PAYS" (id, Nom) VALUES ('KE', 'Kenya');
INSERT INTO "PAYS" (id, Nom) VALUES ('KG', 'Kirghizistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('KI', 'Kiribati');
INSERT INTO "PAYS" (id, Nom) VALUES ('XK', 'Kosovo');
INSERT INTO "PAYS" (id, Nom) VALUES ('KW', 'Koweït');
INSERT INTO "PAYS" (id, Nom) VALUES ('RE', 'La Réunion');
INSERT INTO "PAYS" (id, Nom) VALUES ('LA', 'Laos');
INSERT INTO "PAYS" (id, Nom) VALUES ('LS', 'Lesotho');
INSERT INTO "PAYS" (id, Nom) VALUES ('LV', 'Lettonie');
INSERT INTO "PAYS" (id, Nom) VALUES ('LB', 'Liban');
INSERT INTO "PAYS" (id, Nom) VALUES ('LR', 'Libéria');
INSERT INTO "PAYS" (id, Nom) VALUES ('LY', 'Libye');
INSERT INTO "PAYS" (id, Nom) VALUES ('LI', 'Liechtenstein');
INSERT INTO "PAYS" (id, Nom) VALUES ('LT', 'Lituanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('LU', 'Luxembourg');
INSERT INTO "PAYS" (id, Nom) VALUES ('MK', 'Macédoine');
INSERT INTO "PAYS" (id, Nom) VALUES ('MG', 'Madagascar');
INSERT INTO "PAYS" (id, Nom) VALUES ('MY', 'Malaisie');
INSERT INTO "PAYS" (id, Nom) VALUES ('MW', 'Malawi');
INSERT INTO "PAYS" (id, Nom) VALUES ('MV', 'Maldives');
INSERT INTO "PAYS" (id, Nom) VALUES ('ML', 'Mali');
INSERT INTO "PAYS" (id, Nom) VALUES ('MT', 'Malte');
INSERT INTO "PAYS" (id, Nom) VALUES ('MA', 'Maroc');
INSERT INTO "PAYS" (id, Nom) VALUES ('MQ', 'Martinique');
INSERT INTO "PAYS" (id, Nom) VALUES ('MU', 'Maurice');
INSERT INTO "PAYS" (id, Nom) VALUES ('MR', 'Mauritanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('YT', 'Mayotte');
INSERT INTO "PAYS" (id, Nom) VALUES ('MX', 'Mexique');
INSERT INTO "PAYS" (id, Nom) VALUES ('MD', 'Moldavie');
INSERT INTO "PAYS" (id, Nom) VALUES ('MC', 'Monaco');
INSERT INTO "PAYS" (id, Nom) VALUES ('MN', 'Mongolie');
INSERT INTO "PAYS" (id, Nom) VALUES ('ME', 'Monténégro');
INSERT INTO "PAYS" (id, Nom) VALUES ('MS', 'Montserrat');
INSERT INTO "PAYS" (id, Nom) VALUES ('MZ', 'Mozambique');
INSERT INTO "PAYS" (id, Nom) VALUES ('MM', 'Myanmar');
INSERT INTO "PAYS" (id, Nom) VALUES ('NA', 'Namibie');
INSERT INTO "PAYS" (id, Nom) VALUES ('NR', 'Nauru');
INSERT INTO "PAYS" (id, Nom) VALUES ('NP', 'Népal');
INSERT INTO "PAYS" (id, Nom) VALUES ('NI', 'Nicaragua');
INSERT INTO "PAYS" (id, Nom) VALUES ('NE', 'Niger');
INSERT INTO "PAYS" (id, Nom) VALUES ('NG', 'Nigéria');
INSERT INTO "PAYS" (id, Nom) VALUES ('NU', 'Niue');
INSERT INTO "PAYS" (id, Nom) VALUES ('NO', 'Norvège');
INSERT INTO "PAYS" (id, Nom) VALUES ('NC', 'Nouvelle-Calédonie');
INSERT INTO "PAYS" (id, Nom) VALUES ('NZ', 'Nouvelle-Zélande');
INSERT INTO "PAYS" (id, Nom) VALUES ('OM', 'Oman');
INSERT INTO "PAYS" (id, Nom) VALUES ('UG', 'Ouganda');
INSERT INTO "PAYS" (id, Nom) VALUES ('UZ', 'Ouzbékistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('PK', 'Pakistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('PW', 'Palaos');
INSERT INTO "PAYS" (id, Nom) VALUES ('PA', 'Panama');
INSERT INTO "PAYS" (id, Nom) VALUES ('PG', 'Papouasie-Nouvelle-Guinée');
INSERT INTO "PAYS" (id, Nom) VALUES ('PY', 'Paraguay');
INSERT INTO "PAYS" (id, Nom) VALUES ('NL', 'Pays-Bas');
INSERT INTO "PAYS" (id, Nom) VALUES ('BQ', 'Pays-Bas caribéens');
INSERT INTO "PAYS" (id, Nom) VALUES ('PE', 'Pérou');
INSERT INTO "PAYS" (id, Nom) VALUES ('PH', 'Philippines');
INSERT INTO "PAYS" (id, Nom) VALUES ('PN', 'Pitcairn');
INSERT INTO "PAYS" (id, Nom) VALUES ('PL', 'Pologne');
INSERT INTO "PAYS" (id, Nom) VALUES ('PF', 'Polynésie française');
INSERT INTO "PAYS" (id, Nom) VALUES ('PR', 'Porto Rico');
INSERT INTO "PAYS" (id, Nom) VALUES ('PT', 'Portugal');
INSERT INTO "PAYS" (id, Nom) VALUES ('QA', 'Qatar');
INSERT INTO "PAYS" (id, Nom) VALUES ('HK', 'R.A.S. chinoise de Hong Kong');
INSERT INTO "PAYS" (id, Nom) VALUES ('MO', 'R.A.S. chinoise de Macao');
INSERT INTO "PAYS" (id, Nom) VALUES ('CF', 'République centrafricaine');
INSERT INTO "PAYS" (id, Nom) VALUES ('DO', 'République dominicaine');
INSERT INTO "PAYS" (id, Nom) VALUES ('CZ', 'République tchèque');
INSERT INTO "PAYS" (id, Nom) VALUES ('RO', 'Roumanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('GB', 'Royaume-Uni');
INSERT INTO "PAYS" (id, Nom) VALUES ('RU', 'Russie');
INSERT INTO "PAYS" (id, Nom) VALUES ('RW', 'Rwanda');
INSERT INTO "PAYS" (id, Nom) VALUES ('EH', 'Sahara occidental');
INSERT INTO "PAYS" (id, Nom) VALUES ('BL', 'Saint-Barthélemy');
INSERT INTO "PAYS" (id, Nom) VALUES ('KN', 'Saint-Christophe-et-Niévès');
INSERT INTO "PAYS" (id, Nom) VALUES ('SM', 'Saint-Marin');
INSERT INTO "PAYS" (id, Nom) VALUES ('MF', 'Saint-Martin (partie française)');
INSERT INTO "PAYS" (id, Nom) VALUES ('SX', 'Saint-Martin (partie néerlandaise)');
INSERT INTO "PAYS" (id, Nom) VALUES ('PM', 'Saint-Pierre-et-Miquelon');
INSERT INTO "PAYS" (id, Nom) VALUES ('VC', 'Saint-Vincent-et-les-Grenadines');
INSERT INTO "PAYS" (id, Nom) VALUES ('SH', 'Sainte-Hélène');
INSERT INTO "PAYS" (id, Nom) VALUES ('LC', 'Sainte-Lucie');
INSERT INTO "PAYS" (id, Nom) VALUES ('WS', 'Samoa');
INSERT INTO "PAYS" (id, Nom) VALUES ('AS', 'Samoa américaines');
INSERT INTO "PAYS" (id, Nom) VALUES ('ST', 'Sao Tomé-et-Principe');
INSERT INTO "PAYS" (id, Nom) VALUES ('SN', 'Sénégal');
INSERT INTO "PAYS" (id, Nom) VALUES ('RS', 'Serbie');
INSERT INTO "PAYS" (id, Nom) VALUES ('SC', 'Seychelles');
INSERT INTO "PAYS" (id, Nom) VALUES ('SL', 'Sierra Leone');
INSERT INTO "PAYS" (id, Nom) VALUES ('SG', 'Singapour');
INSERT INTO "PAYS" (id, Nom) VALUES ('SK', 'Slovaquie');
INSERT INTO "PAYS" (id, Nom) VALUES ('SI', 'Slovénie');
INSERT INTO "PAYS" (id, Nom) VALUES ('SO', 'Somalie');
INSERT INTO "PAYS" (id, Nom) VALUES ('SD', 'Soudan');
INSERT INTO "PAYS" (id, Nom) VALUES ('SS', 'Soudan du Sud');
INSERT INTO "PAYS" (id, Nom) VALUES ('LK', 'Sri Lanka');
INSERT INTO "PAYS" (id, Nom) VALUES ('SE', 'Suède');
INSERT INTO "PAYS" (id, Nom) VALUES ('CH', 'Suisse');
INSERT INTO "PAYS" (id, Nom) VALUES ('SR', 'Suriname');
INSERT INTO "PAYS" (id, Nom) VALUES ('SJ', 'Svalbard et Jan Mayen');
INSERT INTO "PAYS" (id, Nom) VALUES ('SZ', 'Swaziland');
INSERT INTO "PAYS" (id, Nom) VALUES ('SY', 'Syrie');
INSERT INTO "PAYS" (id, Nom) VALUES ('TJ', 'Tadjikistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('TW', 'Taïwan');
INSERT INTO "PAYS" (id, Nom) VALUES ('TZ', 'Tanzanie');
INSERT INTO "PAYS" (id, Nom) VALUES ('TD', 'Tchad');
INSERT INTO "PAYS" (id, Nom) VALUES ('TF', 'Terres australes françaises');
INSERT INTO "PAYS" (id, Nom) VALUES ('IO', 'Territoire britannique de l’océan Indien');
INSERT INTO "PAYS" (id, Nom) VALUES ('PS', 'Territoires palestiniens');
INSERT INTO "PAYS" (id, Nom) VALUES ('TH', 'Thaïlande');
INSERT INTO "PAYS" (id, Nom) VALUES ('TL', 'Timor oriental');
INSERT INTO "PAYS" (id, Nom) VALUES ('TG', 'Togo');
INSERT INTO "PAYS" (id, Nom) VALUES ('TK', 'Tokelau');
INSERT INTO "PAYS" (id, Nom) VALUES ('TO', 'Tonga');
INSERT INTO "PAYS" (id, Nom) VALUES ('TT', 'Trinité-et-Tobago');
INSERT INTO "PAYS" (id, Nom) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "PAYS" (id, Nom) VALUES ('TN', 'Tunisie');
INSERT INTO "PAYS" (id, Nom) VALUES ('TM', 'Turkménistan');
INSERT INTO "PAYS" (id, Nom) VALUES ('TR', 'Turquie');
INSERT INTO "PAYS" (id, Nom) VALUES ('TV', 'Tuvalu');
INSERT INTO "PAYS" (id, Nom) VALUES ('UA', 'Ukraine');
INSERT INTO "PAYS" (id, Nom) VALUES ('UY', 'Uruguay');
INSERT INTO "PAYS" (id, Nom) VALUES ('VU', 'Vanuatu');
INSERT INTO "PAYS" (id, Nom) VALUES ('VE', 'Venezuela');
INSERT INTO "PAYS" (id, Nom) VALUES ('VN', 'Vietnam');
INSERT INTO "PAYS" (id, Nom) VALUES ('WF', 'Wallis-et-Futuna');
INSERT INTO "PAYS" (id, Nom) VALUES ('YE', 'Yémen');
INSERT INTO "PAYS" (id, Nom) VALUES ('ZM', 'Zambie');
INSERT INTO "PAYS" (id, Nom) VALUES ('ZW', 'Zimbabwe');
